"use client";

import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export const CONTAINER_TYPES = ["tin", "drum", "carton", "bag"] as const;
export type ContainerType = (typeof CONTAINER_TYPES)[number];

export interface SkuRow {
  id:                number;
  skuCode:           string;
  skuName:           string;
  packSize:          string;
  containerType:     string;
  unitsPerCarton:    number | null;
  productCategoryId: number;
  productCategory:   { name: string };
  productNameId:     number;
  productName:       { name: string };
  baseColourId:      number;
  baseColour:        { name: string };
  isActive:          boolean;
}

interface Lookup { id: number; name: string; }

interface SkuSheetProps {
  open:         boolean;
  onOpenChange: (open: boolean) => void;
  editing:      SkuRow | null;
  onSaved:      (sku: SkuRow) => void;
}

const EMPTY = {
  skuCode:           "",
  skuName:           "",
  packSize:          "",
  containerType:     "tin" as ContainerType,
  unitsPerCarton:    "",
  productCategoryId: "",
  productNameId:     "",
  baseColourId:      "",
  isActive:          true,
};

function buildForm(editing: SkuRow | null) {
  if (!editing) return EMPTY;
  return {
    skuCode:           editing.skuCode,
    skuName:           editing.skuName,
    packSize:          editing.packSize,
    containerType:     editing.containerType as ContainerType,
    unitsPerCarton:    editing.unitsPerCarton?.toString() ?? "",
    productCategoryId: editing.productCategoryId.toString(),
    productNameId:     editing.productNameId.toString(),
    baseColourId:      editing.baseColourId.toString(),
    isActive:          editing.isActive,
  };
}

export function SkuSheet({ open, onOpenChange, editing, onSaved }: SkuSheetProps) {
  const [form,         setForm]         = useState(buildForm(editing));
  const [fieldErrors,  setFieldErrors]  = useState<Record<string, string>>({});
  const [saving,       setSaving]       = useState(false);
  const [categories,   setCategories]   = useState<Lookup[]>([]);
  const [productNames, setProductNames] = useState<Lookup[]>([]);
  const [baseColours,  setBaseColours]  = useState<Lookup[]>([]);

  // Track whether skuName was auto-generated so we don't overwrite manual edits
  const autoGenerated = useRef(false);

  // Load categories and base colours once on mount
  useEffect(() => {
    fetch("/api/admin/product-categories")
      .then((r) => r.json())
      .then(setCategories)
      .catch(() => {});
    fetch("/api/admin/base-colours")
      .then((r) => r.json())
      .then(setBaseColours)
      .catch(() => {});
  }, []);

  // Reset form when sheet opens
  useEffect(() => {
    if (open) {
      const f = buildForm(editing);
      setForm(f);
      setFieldErrors({});
      autoGenerated.current = false;
      if (f.productCategoryId) {
        fetch(`/api/admin/product-names?categoryId=${f.productCategoryId}`)
          .then((r) => r.json())
          .then(setProductNames)
          .catch(() => {});
      } else {
        setProductNames([]);
      }
    }
  }, [open, editing]);

  // Reload product names when category changes
  useEffect(() => {
    if (!form.productCategoryId) { setProductNames([]); return; }
    fetch(`/api/admin/product-names?categoryId=${form.productCategoryId}`)
      .then((r) => r.json())
      .then(setProductNames)
      .catch(() => {});
  }, [form.productCategoryId]);

  // Auto-suggest skuName when productName + packSize + baseColour are all set
  useEffect(() => {
    if (!form.productNameId || !form.packSize.trim() || !form.baseColourId) return;
    if (!autoGenerated.current && form.skuName.trim()) return; // user has a manual value

    const pName  = productNames.find((n) => n.id.toString() === form.productNameId)?.name ?? "";
    const colour = baseColours.find((c) => c.id.toString() === form.baseColourId)?.name ?? "";
    if (!pName || !colour) return;

    const suggested = `${pName} ${form.packSize.trim()} ${colour}`;
    autoGenerated.current = true;
    setForm((prev) => ({ ...prev, skuName: suggested }));
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [form.productNameId, form.packSize, form.baseColourId]);

  function setField<K extends keyof typeof form>(key: K, value: (typeof form)[K]) {
    if (key === "skuName") autoGenerated.current = false;
    if (key === "productCategoryId") {
      setForm((prev) => ({ ...prev, [key]: value, productNameId: "" }));
      setFieldErrors((prev) => { const n = { ...prev }; delete n[key as string]; delete n.productNameId; return n; });
      return;
    }
    setForm((prev) => ({ ...prev, [key]: value }));
    setFieldErrors((prev) => { const n = { ...prev }; delete n[key as string]; return n; });
  }

  function validate(): boolean {
    const errs: Record<string, string> = {};
    if (!form.skuCode.trim())        errs.skuCode           = "SKU code is required.";
    if (!form.skuName.trim())        errs.skuName           = "SKU name is required.";
    if (!form.packSize.trim())       errs.packSize          = "Pack size is required.";
    if (!form.productCategoryId)     errs.productCategoryId = "Category is required.";
    if (!form.productNameId)         errs.productNameId     = "Product name is required.";
    if (!form.baseColourId)          errs.baseColourId      = "Base colour is required.";
    if (form.unitsPerCarton && (isNaN(parseInt(form.unitsPerCarton, 10)) || parseInt(form.unitsPerCarton, 10) <= 0)) {
      errs.unitsPerCarton = "Must be a positive integer.";
    }
    setFieldErrors(errs);
    return Object.keys(errs).length === 0;
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!validate()) return;
    setSaving(true);

    const body = {
      skuCode:           form.skuCode.trim().toUpperCase(),
      skuName:           form.skuName.trim(),
      packSize:          form.packSize.trim(),
      containerType:     form.containerType,
      unitsPerCarton:    form.unitsPerCarton ? parseInt(form.unitsPerCarton, 10) : null,
      productCategoryId: parseInt(form.productCategoryId, 10),
      productNameId:     parseInt(form.productNameId, 10),
      baseColourId:      parseInt(form.baseColourId, 10),
      isActive:          form.isActive,
    };

    try {
      const url    = editing ? `/api/admin/skus/${editing.id}` : "/api/admin/skus";
      const method = editing ? "PATCH" : "POST";
      const res    = await fetch(url, {
        method,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      const data = await res.json();
      if (!res.ok) {
        if (res.status === 409) {
          setFieldErrors({ skuCode: "SKU code already exists." });
        } else {
          toast.error(data.error ?? "Failed to save.");
        }
        return;
      }
      toast.success(editing ? "SKU updated." : `SKU "${data.skuCode}" created.`);
      onSaved(data);
      onOpenChange(false);
    } catch {
      toast.error("Network error.");
    } finally {
      setSaving(false);
    }
  }

  const isNotDrumOrBag = form.containerType !== "drum" && form.containerType !== "bag";

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent className="w-full sm:max-w-2xl overflow-y-auto">
        <SheetHeader>
          <SheetTitle>{editing ? "Edit SKU" : "Add SKU"}</SheetTitle>
        </SheetHeader>

        <form onSubmit={handleSubmit} className="oa-sheet-form flex flex-col gap-5 px-6 pb-0">

          {/* ── Section 1: Identity ─────────────────────────────────────────── */}
          <div className="space-y-4">
            <p className="oa-form-section">Identity</p>

            <div className="space-y-1.5">
              <Label>SKU Code <span className="text-destructive">*</span></Label>
              <Input
                value={form.skuCode}
                onChange={(e) => setField("skuCode", e.target.value.toUpperCase())}
                placeholder="e.g. AQT-4L-WB"
                className="font-mono"
              />
              {fieldErrors.skuCode && <p className="text-xs text-destructive">{fieldErrors.skuCode}</p>}
            </div>

            <div className="space-y-1.5">
              <Label>
                SKU Name <span className="text-destructive">*</span>
                <span className="ml-1.5 text-xs font-normal text-slate-400">(auto-fills from selections below)</span>
              </Label>
              <Input
                value={form.skuName}
                onChange={(e) => setField("skuName", e.target.value)}
                placeholder="e.g. Aquatech 4L White Base"
              />
              {fieldErrors.skuName && <p className="text-xs text-destructive">{fieldErrors.skuName}</p>}
            </div>
          </div>

          {/* ── Section 2: Classification ───────────────────────────────────── */}
          <div className="space-y-4">
            <p className="oa-form-section">Classification</p>

            <div className="space-y-1.5">
              <Label>Category <span className="text-destructive">*</span></Label>
              <Select
                value={form.productCategoryId}
                onValueChange={(v) => setField("productCategoryId", v ?? "")}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select category" />
                </SelectTrigger>
                <SelectContent>
                  {categories.map((c) => (
                    <SelectItem key={c.id} value={c.id.toString()}>{c.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {fieldErrors.productCategoryId && <p className="text-xs text-destructive">{fieldErrors.productCategoryId}</p>}
            </div>

            <div className="space-y-1.5">
              <Label>Product Name <span className="text-destructive">*</span></Label>
              <Select
                value={form.productNameId}
                onValueChange={(v) => setField("productNameId", v ?? "")}
                disabled={!form.productCategoryId}
              >
                <SelectTrigger>
                  <SelectValue placeholder={form.productCategoryId ? "Select product name" : "Select category first"} />
                </SelectTrigger>
                <SelectContent>
                  {productNames.map((n) => (
                    <SelectItem key={n.id} value={n.id.toString()}>{n.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {fieldErrors.productNameId && <p className="text-xs text-destructive">{fieldErrors.productNameId}</p>}
            </div>

            <div className="space-y-1.5">
              <Label>Base / Colour <span className="text-destructive">*</span></Label>
              <Select
                value={form.baseColourId}
                onValueChange={(v) => setField("baseColourId", v ?? "")}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select base colour" />
                </SelectTrigger>
                <SelectContent>
                  {baseColours.map((c) => (
                    <SelectItem key={c.id} value={c.id.toString()}>{c.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {fieldErrors.baseColourId && <p className="text-xs text-destructive">{fieldErrors.baseColourId}</p>}
            </div>
          </div>

          {/* ── Section 3: Pack Details ─────────────────────────────────────── */}
          <div className="space-y-4">
            <p className="oa-form-section">Pack Details</p>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <Label>Pack Size <span className="text-destructive">*</span></Label>
                <Input
                  value={form.packSize}
                  onChange={(e) => setField("packSize", e.target.value)}
                  placeholder="e.g. 1L, 4L, 20kg"
                />
                {fieldErrors.packSize && <p className="text-xs text-destructive">{fieldErrors.packSize}</p>}
              </div>

              <div className="space-y-1.5">
                <Label>Container Type <span className="text-destructive">*</span></Label>
                <Select
                  value={form.containerType}
                  onValueChange={(v) => setField("containerType", (v ?? "tin") as ContainerType)}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {CONTAINER_TYPES.map((t) => (
                      <SelectItem key={t} value={t}>
                        {t.charAt(0).toUpperCase() + t.slice(1)}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div className="space-y-1.5">
              <Label>
                Units / Carton
                <span className="ml-1 text-xs font-normal text-slate-400">(optional)</span>
              </Label>
              <Input
                type="number" min="1" step="1"
                value={form.unitsPerCarton}
                onChange={(e) => setField("unitsPerCarton", e.target.value)}
                placeholder={isNotDrumOrBag ? "e.g. 4, 24" : "Not applicable"}
                disabled={!isNotDrumOrBag}
              />
              {!isNotDrumOrBag && (
                <p className="text-xs text-slate-400">Not applicable for drums / bags</p>
              )}
              {fieldErrors.unitsPerCarton && (
                <p className="text-xs text-destructive">{fieldErrors.unitsPerCarton}</p>
              )}
            </div>

            <p className="text-xs text-slate-400 rounded-md bg-slate-50 border px-3 py-2">
              Weight is captured from the OBD import file at order time.
            </p>

            {/* Is Active */}
            <label className="flex items-center justify-between p-3 rounded-lg border border-[#e5e7eb] bg-[#f7f8fa] cursor-pointer hover:bg-[#eef2ff] hover:border-[#c7d2fe] transition-all">
              <div>
                <div className="text-sm font-medium text-[#111827]">Active</div>
                <div className="text-xs text-[#6b7280] mt-0.5">Inactive SKUs cannot be added to new orders</div>
              </div>
              <Switch
                checked={form.isActive}
                onCheckedChange={(v) => setField("isActive", v)}
                className="data-[state=checked]:bg-[#1a237e]"
              />
            </label>
          </div>

          <div className="sticky bottom-0 bg-white border-t border-[#e5e7eb] -mx-6 px-6 py-4 flex gap-3 mt-6">
            <Button type="button" variant="outline" className="flex-1 h-10 text-sm border-[#e5e7eb] text-[#374151] hover:bg-[#f7f8fa] rounded-lg oa-btn-ghost" onClick={() => onOpenChange(false)} disabled={saving}>Cancel</Button>
            <Button type="submit" className="flex-1 h-10 text-sm bg-[#1a237e] hover:bg-[#283593] text-white rounded-lg font-semibold oa-btn-primary" disabled={saving}>{saving ? "Saving…" : editing ? "Save Changes" : "Create SKU"}</Button>
          </div>
        </form>
      </SheetContent>
    </Sheet>
  );
}
